version: '3.8'
services:
  backend:
    build: .
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"  # Map the container port to the host port
    environment:
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - PORT_DATABASE=${PORT_DATABASE}
      - PORT_SERVER=${PORT_SERVER}
      - PORT_NGINX_HTTP=${PORT_NGINX_HTTP}
      - PORT_NGINX_HTTPS=${PORT_NGINX_HTTPS}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      db:
        condition: service_healthy  # Ensure MySQL is ready before starting the backend
    volumes:
      - .:/usr/src/app  # Mount the local directory to the container
    command: ["bash", "./wait-for-it.sh", "db:${PORT_DATABASE}", "--", "npm", "start"]  # Wait for DB to be ready

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "${PORT_DATABASE}:${PORT_DATABASE}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5  # This healthcheck ensures MySQL is ready before backend starts

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "${PORT_NGINX_HTTP}:${PORT_NGINX_HTTP}"     # HTTP
      - "${PORT_NGINX_HTTPS}:${PORT_NGINX_HTTPS}"   # HTTPS
    volumes:
      - ./certs:/etc/letsencrypt
    depends_on:
      - backend    

volumes:
  db_data: