# Use the official Nginx image
FROM nginx:alpine

# Copy custom Nginx configuration to container
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE ${PORT_NGINX_HTTP}
EXPOSE ${PORT_NGINX_HTTPS}

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
